### ISSUE TITLE
Issue with jumping from 0x100000 to 0xC0000000

### ISSUE THREAD

**Issue by IlanVinograd** [IlanVinograd/OS_32Bit#28]
## Create a New Page Table for Higher Half Kernel:

- Allocate a new page table in the init_paging() function for virtual addresses starting at 0xC0000000.
- Add this new page table to the page directory at entry #768 (which corresponds to virtual addresses 0xC0000000 and above).

```c
uint32_t new_page_table[1024] __attribute__((aligned(4096)));
page_directory[768] = ((uint32_t)new_page_table) | PAGE_PRESENT | PAGE_WRITABLE;
```

## Map Physical Address 0x100000 to Virtual Address 0xC0000000:

- Use a loop to fill the new page table with entries that map virtual addresses starting from 0xC0000000 to the physical addresses starting at 0x100000.

```c
for (int i = 0; i < num_pages; i++) {
    new_page_table[i] = (0x100000 + i * PAGE_SIZE) | PAGE_PRESENT | PAGE_WRITABLE;
}
```

## Load the Updated Page Directory into CR3:

- After setting up the new page table, reload the page directory into the CR3 register to apply the new mapping.
```c
load_page_directory((uint32_t)page_directory);
```

## Jump to Kernel at Virtual Address 0xC0000000:

- Once paging is enabled, perform a far jump to the kernel's virtual address at 0xC0000000 to continue execution in the higher half.

need to do something like this code from NASM.
```nasm
jmp 0x08:0xC0000000
```

**Comment by mpetch** [comment]
#34 resolves most of the issues.

**Comment by IlanVinograd** [comment]
Hi @mpetch ,

Thanks again for your help with setting up the higher half jump and the paging. I’ve made the adjustments to the GDT and TSS as you suggested, and pushed the changes to the 'target' branch. However, I’m running into an issue where the jump to the kernel doesn’t seem to be working after enabling paging. I’ve been trying to debug it, but I’m not sure if I missed something with the GDT or TSS setup in the higher half.

I’d appreciate it if you could take a look at the 'target' branch and point me in the right direction. I want to make sure I understand the core issue and can resolve it myself. Let me know if you have any suggestions!

Thanks!

**Comment by IlanVinograd** [comment]
I’ve been reviewing the code, and I think the issue might be related to the kernel_entry.s file. It could be what’s preventing the jump to the kernel after enabling paging. I’m still debugging it but wanted to mention this in case it’s worth checking out.

**Comment by IlanVinograd** [comment]
Or do I need to set up the GDT and TSS the same way I set up the IDT?
