### ISSUE TITLE
Developing bootloader - STAGE1

### ISSUE THREAD

**Issue by danielLublinsky** [IlanVinograd/OS_32Bit#4]
### Developing Stage1 - Bootloader
after #2, #3  is complete we can start working on stage 1,
- create stage1.asm file at /bootloader/stage1
- add stage1.asm to makeFile
- add stage1.o to link.ld
- then Create disk from docker, If all OK 👌 then We can move on...

**Comment by danielLublinsky** [comment]
@IlanVinograd, when reading the disk, you set the cylinder to 01, but the stage 1 and stage 2 are on the same cylinder
The cylinder should be 00.

**Comment by IlanVinograd** [comment]
@danielLublinsky Wouldn't it be better to keep it separate for better organization?

**Comment by danielLublinsky** [comment]
@IlanVinograd 

Cylinders are big, very big.
When I come to mapping the file system, your allocated space on the disk must be clean of any other data,
Basically, it has to come after stage 2.

So if you put stage 2 on Cylinder 1
You are wasting a lot of memory that can be allocated for the file system
 
The bootloader is a tiny part of the os, and it should be as minimal as possible.

**Comment by IlanVinograd** [comment]
@danielLublinsky ok

**Comment by IlanVinograd** [comment]
Closed
