### ISSUE TITLE
Implement "clear" Command for Shell

### ISSUE THREAD

**Issue by IlanVinograd** [IlanVinograd/OS_32Bit#60]
# Good First Issue: Implement "clear" Command for Shell

## Objective
Add a new shell command `clear` that clears the screen and resets the cursor to the top-left corner.

## Task Details
1. **Add Command Handling**
   - Update the shell input handling logic to recognize the command `clear`.

2. **Clear Screen Functionality**
   - Use the existing `clearScreen()` function in `vga.c` to clear the screen content.
   - Reset the cursor position to the starting point using `setCursorPosition(2, 0)` to ensure the shell prompt is displayed after the header.

3. **Integration**
   - Ensure the `clear` command does not interfere with other shell commands.
   - Test the functionality by executing the `clear` command in the shell and verifying that the screen is cleared, and the cursor is reset correctly.

## Acceptance Criteria
- Typing `clear` in the shell should clear the screen and reset the cursor to the prompt position.
- No impact on other shell functionalities.

## Hints
- Look at the existing `handleBackgroundColor()` function for reference on how commands are handled in the shell.
- Use the `scroll_screen()` function as a fallback if additional modifications are needed to ensure proper cursor placement after clearing.

**Comment by Malone-AI** [comment]
I have implemented "clear" command for shell, can you assign this issue to me? I'll appreciate it if you can assign it to me.I will propose PR after sorting it out.
