### ISSUE TITLE
Implement "free" Command for Shell

### ISSUE THREAD

**Issue by IlanVinograd** [IlanVinograd/OS_32Bit#63]
# Good First Issue: Implement "free" Command for Shell

## Objective
Add a new shell command `free` that displays memory usage information, including total memory, used memory, and free memory.

## Task Details

1. **Add Command Handling**
   - Update the shell input handling logic to recognize the `free` command.

2. **Display Memory Information**
   - Integrate with the memory management module to retrieve:
     - Total memory available.
     - Memory currently in use.
     - Free memory.
   - Format and display the information in a user-friendly way. Examples of output:
     ```
     Total Memory: 4 MB
     Used Memory: 2 MB
     Free Memory: 2 MB
     ```
     or
     ```
     Total Memory  |IIIIIIIII-----------| 
     Used Memory   |IIIIIIIIIIIII-------| 
     Free Memory   |IIIIIIIIIIIIIII-----| 
     ```
     or
     ```
     use your imagination :D
     ```
   - Optionally, allow for flexible formatting to support future extensions (e.g., display in bytes, KB, or MB).

3. **Integration**
   - Ensure the `free` command integrates seamlessly with the existing shell functionalities.
   - Avoid any interference with other commands.

4. **Testing**
   - Test the `free` command in scenarios with various memory usage patterns:
     - After allocating and freeing memory blocks.
     - With fragmented memory and near full usage.
   - Verify that the displayed information is accurate and consistent under all conditions.

## Acceptance Criteria
- Typing `free` in the shell should display memory statistics in a clear and readable format.
- The output should provide accurate details on:
  - Total memory.
  - Used memory.
  - Free memory.
- The functionality should not affect or interfere with other shell commands.

## Hints
- Use the existing functions in `memory_manager.c` and `bitmap.c` to calculate memory statistics.
- Leverage the `printf()` implementation in `vga.c` to format and display the output.
- Test edge cases where memory is fully allocated or heavily fragmented to ensure the `free` command provides reliable information.

## For Testing
- there is `test` command to create simple task.
## Notes
- Consider designing the command to support additional options in the future (e.g., verbose output or detailed memory usage by tasks).

**Comment by Malone-AI** [comment]
It looks interesting, I will try it after my final examination

**Comment by Malone-AI** [comment]
@IlanVinograd I appreciate you assigning it to me. I will spare no effort to finish it

**Comment by IlanVinograd** [comment]
well done

**Comment by Malone-AI** [comment]
Thank you for your recognition and support and for providing such an opportunity
